stages:
 - config
 - build

config:
  stage: config
  script: "./bootstrap; ./configure;"
  artifacts:
      untracked: true
      
build:
  stage: build
  script: "make -j8"
    
tests:
  stage: build
  script: "make check -j8"
